title: the type
description: Typography Blog
header_text: ""
footer_text: Copyright 2020 Jessica King
header_feature_image: ../uploads/bannerimagewithtext.png
bannerheight: 100vh
logo: ../uploads/logo-1.png
favicon: ../uploads/favicon-16x16.png
gridlayout: false
fixednavbar: false
upzoom: true
