title: the type
description: Typography Blog
header_text: ""
footer_text: Copyright 2020 Jessica King
header_feature_image: ../uploads/banner-image-title.png
bannerheight: 100vh
logo: ../uploads/the-type-logo-.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
